/**
 * English UI labels for dynamic lookups (sort modes, grid sizes, filter chips).
 * Static copy lives inline in the components.
 */
export const labels = {
  // Navigation
  catalog: "Catalog",
  store: "Store",
  deck_builder: "Deck Builder",
  sign_in: "Sign In",
  register: "Register",
  sign_out: "Sign Out",
  my_profile: "My Profile",
  store_dashboard: "Store Dashboard",
  platform_owner: "Platform Owner",
  store_admin: "Store Admin",
  collector: "Collector",
  account: "Account",

  // Controls & Toolbar
  search_placeholder: "Search cards by name, number, or artist...",
  sort_number_asc: "Card Number (Asc)",
  sort_number_desc: "Card Number (Desc)",
  sort_rarity_high: "Rarity (High to Low)",
  sort_rarity_low: "Rarity (Low to High)",
  sort_price_low: "Price (Low to High)",
  sort_price_high: "Price (High to Low)",
  sort_qty_high: "Quantity (High to Low)",
  sort_qty_low: "Quantity (Low to High)",
  sort_name_asc: "Name (A to Z)",
  sort_name_desc: "Name (Z to A)",
  all: "All",
  owned: "Owned",
  have: "Owned",
  playset: "Playset",
  missing: "Missing",
  small: "Small",
  normal: "Normal",
  large: "Large",
  export: "Export",
  import: "Import",
  reset: "Reset",
  select_game: "Select Game",
  soon: "Soon",

  // Filter Sidebar
  filters: "Filters",
  reset_filters: "Reset Filters",
  search_sets: "Search sets...",
  all_sets: "All Sets",
  set: "Set",
  type: "Type",
  domain: "Domain",
  energy_type: "Energy Type",
  rarity: "Rarity",
  card_variant: "Card Variant",
  foil_only: "Foil Only",
  base_set_only: "Base Set Only (1 - Max)",
  sp_cards: "SP Cards",
  signed_cards: "Signed",
  overnumbered: "Overnumbered",
  alt_art: "Alt Art",
  cost: "Cost",
  any_cost: "Any Cost",
  all_types: "All Types",
  all_domains: "All Domains",
  all_rarities: "All Rarities",

  // Card Details & Collection
  collected: "Collected",
  foil_collected: "Foil Collected",
  not_collected: "Not Collected",
  copy_link: "Copy Link",
  link_copied: "Link copied to clipboard!",
  view_details: "View Details",
  close: "Close",
  domains: "Domains",
  might: "Might",
  energy: "Energy",
  power_cost: "Power Cost",
  recycle_rune: "Recycle Rune",
  ability: "Ability",
  flavor_text: "Flavor Text",
  artist: "Artist",
  signed_edition: "Signed Edition",
  overnumbered_edition: "Overnumbered Edition",
  alt_art_edition: "Alt Art",
  foil_edition: "Foil",
  my_collection_tracker: "My Collection Tracker",
  total_copies: "Total Copies",
  normal_copy: "Regular Copy",
  foil_finish: "Foil Finish",
  condition: "Condition",
  price: "Price",
  in_stock: "In Stock",
  reserve_on_messenger: "Reserve on Messenger",
  check_on_cardmarket: "Check on Cardmarket",
  back_to_catalog: "Back to catalog",
  no_image: "No image uploaded",
  base_set: "Base Set",
  tags: "Tags",

  // Buying & Checkout
  buy_now: "Buy Now",
  checkout: "Checkout",
  cart: "Cart",
  my_cart: "My Cart",
  add_to_cart: "Add to Cart",
  added_to_cart: "Added to Cart!",
  cart_empty: "Your cart is empty",
  cart_empty_desc: "Browse the store and add cards to your cart.",
  proceed_to_checkout: "Proceed to Checkout",
  clear_cart: "Clear Cart",
  place_order: "Confirm Order",
  placing_order: "Placing Order…",
  order_success: "Order Placed Successfully!",
  order_success_desc: "Thank you for your order! We have received your order and are preparing it.",
  shipping_information: "Customer & Shipping Information",
  full_name: "Full Name",
  full_name_placeholder: "e.g. Jane Doe",
  contact_email: "Email Address",
  contact_email_placeholder: "e.g. name@example.com",
  contact_phone: "Phone Number",
  contact_phone_placeholder: "e.g. +36 30 123 4567",
  postal_code: "Postal Code",
  postal_code_placeholder: "e.g. 1011",
  city: "City",
  city_placeholder: "e.g. Budapest",
  street_address: "Street Address",
  street_address_placeholder: "e.g. Main St.",
  house_number: "House / Apt / Door",
  house_number_placeholder: "e.g. 12/B, Floor 2, Door 4",
  shipping_address: "Shipping Address",
  shipping_address_placeholder: "Street address, City, Postal code",
  save_info_locally: "Save shipping details for next time (stored on this device only)",
  order_notes: "Order Notes / Special Requests",
  order_notes_placeholder: "Any special delivery instructions or requests…",
  payment_notice_title: "Payment Information",
  payment_notice: "No online payment required upfront. Pay upon delivery, cash on pickup, or via bank transfer.",
  order_number: "Order Number",
  order_date: "Order Date",
  order_total: "Order Total",
  view_in_profile: "View Order History",
  continue_shopping: "Continue Browsing",
  quantity: "Quantity",
  unit_price: "Unit Price",
  insufficient_stock: "Selected quantity exceeds available stock.",
  items_count: "items",
  item_count_singular: "item",
  remove_item: "Remove",
  reservation_timer: "Items reserved for:",
  reservation_expired_cart: "Your 15-minute reservation expired. Items were returned to available stock.",
  reservation_checkout_notice: "Items reserved for 15 minutes to complete your order.",
  reservation_afk_notice: "Reservation expired due to inactivity. Stock will be verified when placing your order.",
  checking_stock: "Checking stock…",
  stock_unavailable_error: "Unable to proceed: Some items are no longer available in the requested quantity.",
  order_reservation_expired_error: "Reservation expired and this item is no longer available in stock. Order was not placed.",
  out_of_stock: "Out of Stock",
  requested: "Requested",
  no_orders_status: "No orders found matching this status filter.",
  main_deck: "Main Deck",
  payment_method: "Payment Method",
  stripe_payment: "Stripe (Card / Apple & Google Pay)",
  stripe_desc: "Instant & encrypted: Apple Pay, Google Pay, Visa, Mastercard",
  barion_payment: "Barion Smart Gateway",
  barion_desc: "Direct bankcard & Barion digital wallet with 0% fee",
  cod_payment: "Bank Transfer / Pay on Delivery",
  cod_desc: "Direct bank transfer or cash upon courier parcel arrival",
  pay_with_stripe: "Pay with Stripe",
  pay_with_barion: "Pay with Barion",
  cancel_order: "Cancel Order",
  theme_dark: "Generic Dark",
  theme_dark_desc: "Clean, neutral deep slate dark mode",
  payment_status_paid: "Paid",
  payment_status_pending: "Payment Pending",
  payment_status_refunded: "Refunded",
  pay_now: "Pay Now",
  payment_method_direct: "Cash / Direct Transfer",
  payment_status_completed: "Arranged with Seller",
  payment_processing: "Processing Payment...",
  payment_successful: "Payment Successful",
  payment_failed: "Payment Failed",
  test_mode_badge: "Test Sandbox Mode",
  stripe_modal_title: "Stripe Secure Checkout",
  barion_modal_title: "Barion Smart Gateway",
  card_number: "Card Number",
  card_expiry: "Expiry (MM/YY)",
  card_cvc: "CVC",
  cardholder_name: "Cardholder Name",
  demo_autofill: "Fill Test Card",

  // Export & Import Modals
  export_collection: "Export Collection",
  export_missing_cards: "Export Missing Cards",
  tab_owned_cards: "Owned Cards",
  tab_missing_cards: "Missing Cards (Want-List)",
  copy_missing_formatted: "Copy Detailed Want-List",
  copy_missing_simple: "Copy Simple Want-List",
  download_missing_txt: "Download Text File (.txt)",
  download_missing_json: "Download JSON File (.json)",
  import_collection: "Import Collection",
  copy_formatted_list: "Copy Formatted Card List",
  copy_simple_list: "Copy Simple Card Names",
  download_json_backup: "Download Collection File (JSON)",
  copy_raw_json: "Copy Raw JSON to Clipboard",
  choose_file: "Choose File...",
  import_btn: "Import Cards",

  // Profile & Cloud
  user_account: "User Account",
  edit: "Edit",
  save: "Save",
  saving: "Saving…",
  cancel: "Cancel",
  order_history: "Order History",
  no_orders: "No orders yet.",
  total: "Total",
  status: "Status",
  date: "Date",
  save_to_cloud: "Save to Cloud Database",
  saved_to_cloud: "Collection successfully saved to your cloud account!",
  restore_from_cloud: "Restore from Cloud Account",
  restored_from_cloud: "Collection restored from cloud!",
  orders_subheading:
    "Track the fulfillment and shipping status of your orders",
  loading_orders: "Loading your orders…",
  browse_store: "Browse Store",
  no_orders_placed:
    "You have not placed any orders yet. Browse our store to find rare cards and singles.",
  order_all: "All",
  order_pending: "Pending",
  order_processing: "Processing",
  order_shipped: "Shipped",
  order_delivered: "Delivered",

  // Auth Modal
  welcome_back: "Welcome Back",
  create_account: "Create an Account",
  email_address: "Email Address",
  password: "Password",
  display_name: "Display Name",
  need_account: "Don't have an account? Register",
  already_account: "Already have an account? Sign In",

  // Deck Builder
  save_deck: "Save Deck",
  deck_name: "Deck Name",
  import_deck: "Import Deck",
  export_deck: "Export Deck",
  download_current_deck: "Download Current Deck (JSON)",
  copy_decklist: "Copy Decklist to Clipboard",
  clear_deck: "Clear Deck",
  new_deck: "New Deck",
  saved_decks: "Saved Decks",
  cards_in_deck: "Cards in Deck",
  deck_limits: "Deck Limits",
  browse: "Browse",
  legend_zone: "Legend Zone",
  chosen_champion: "Chosen Champion",
  rune_deck: "Rune Deck",
  battlefields: "Battlefields",
  sideboard: "Sideboard",
  active_badge: "ACTIVE",
  empty: "Empty",
  no_legend_selected: "No Legend selected",
  no_champion_selected: "No Champion selected",
  allowed_domains: "Allowed Domains",
  select_legend_prompt:
    "Select your Legend first — it determines which domains you can play.",
  search_legends: "Search Legends…",
  search_cards: "Search cards…",
  owned_only: "Owned Only",
  only_show_owned: "Only Show Owned Cards",
  matching_cards_owned: "matching cards owned in your collection",
  cost_range: "Cost Range",
  load_deck: "Load Deck",
  delete: "Delete",
  no_saved_decks: "No saved decks found.",
  backup_all_decks: "Backup All Saved Decks",
  statistics: "Statistics",
  deck_statistics: "Deck Statistics",
  avg_cost: "Average Cost",
  cost_curve: "Cost Curve",
  domain_breakdown: "Domain Distribution",
  type_breakdown: "Card Types",
  rarity_breakdown: "Rarities",
} as const;

export type LabelKey = keyof typeof labels;

export function t(key: LabelKey): string {
  return labels[key] || key;
}
